:construction_worker: Fix broken Android build on Ubuntu
Add missing system dependencies.
The error during the `buildozer android debug` step was:
```
configure.ac:215: error: possibly undefined macro: LT_SYS_SYMBOL_USCORE
autoreconf: error: /usr/bin/autoconf failed with exit status: 1
```
This is well documented in the libffi recipe, refs:
https://github.com/kivy/python-for-android/blob/v2024.01.21/pythonforandroid/recipes/libffi/__init__.py

Bump the default Android API level from 31 to 33.
The error during the `buildozer android release` step was:
```
Error: Google Play requires that apps target API level 33 or higher. [ExpiredTargetSdkVersion]
<uses-sdk android:minSdkVersion="21" android:targetSdkVersion="31" />
```

Also update the `_p4a_have_aab_support()` method from `android.py` to not show
the output of the `aab -h` command to reduce logs and not confuse the user.